# Generated by Django 5.2.1 on 2025-06-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customerotpsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('midtrans_qris', 'Midtrans QRIS'), ('midtrans_va', 'Midtrans Virtual Account'), ('midtrans_ewallet', 'Midtrans E-Wallet')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Processing', max_length=50),
        ),
    ]
