# Generated by Django 5.2.1 on 2025-07-29 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_order_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='SalesReport',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
