# Generated by Django 5.2.1 on 2025-07-29 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_cart_product_remove_cart_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount_paid',
            new_name='total_price',
        ),
    ]
