# Generated by Django 5.2.1 on 2025-07-29 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_amount_paid_payment_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='total_price',
            new_name='amount',
        ),
    ]
